{% set name = "mth5" %}
{% set version = "0.6.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mth5-{{ version }}.tar.gz
  sha256: 161a8cc27284ce6c225f3a47019100e71cd8d2cd7ee933779d222eed746d89b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py
    - matplotlib-base
    - numpy
    - obspy
    - pandas
    - pyyaml
    - scipy
    - xarray
    - mt-metadata >=1.0.0
    - email-validator
    - loguru

test:
  imports:
    - mth5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mth5
  summary: Archivable and exchangeable format for magnetotelluric data
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kujaku11
    - kkappler
    - lheagy
