{% set name = "mth5" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mth5-{{ version }}.tar.gz
  sha256: e618d6bc6f7c0219ffa00c7ab2bba13dc4e0fafcec8d717a1c7e52371cbd3b43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pytest-runner
    - pip
  run:
    - python >=3.7
    - h5py
    - matplotlib-base
    - numpy
    - obspy
    - pandas
    - pyyaml
    - scipy
    - xarray
    - mt-metadata
    - loguru

test:
  imports:
    - mth5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mth5
  summary: Archivable and exchangeable format for magnetotelluric data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - kkappler
    - lheagy
